services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: tobiasreadingdocs-website:latest
    ports:
      - "80:80"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge